# Generated by Django 6.1.1 on 2026-09-14 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('os_summary', models.CharField(blank=True, max_length=255)),
                ('deep_cve_lookup', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('system', 'System Configuration'), ('network', 'Network / Open Ports'), ('software', 'Installed Software')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True, help_text='Raw detail supporting this finding')),
                ('mitigation', models.TextField(blank=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.scanrun')),
            ],
            options={
                'ordering': ['-severity', 'category', 'title'],
            },
        ),
    ]
