# Generated by Django 6.1.1 on 2026-09-15 11:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrun',
            name='client_label',
            field=models.CharField(blank=True, help_text='Optional label the submitter gave this scan', max_length=150),
        ),
        migrations.AddField(
            model_name='scanrun',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='scanrun',
            name='submitted_via_api',
            field=models.BooleanField(default=False),
        ),
    ]
